// packages/web/src/components/AppErrorFallback.tsx
import { Link } from 'react-router-dom';
import { useT } from '../i18n';

/**
 * What ErrorBoundary shows in place of a crashed tree. Split out as its own component so
 * it can use the translation hook — an error boundary has to be a class, which cannot.
 */
export default function AppErrorFallback({ retry }: { retry: () => void }) {
  const t = useT();
  return (
    <div className="page error-page" role="alert">
      <h1>{t.error.title}</h1>
      <p className="error-body">{t.error.body}</p>
      <div className="error-actions">
        <button type="button" className="btn-submit btn-link" onClick={retry}>
          {t.error.retry}
        </button>
        <Link className="btn-submit btn-link" to="/">
          {t.error.home}
        </Link>
      </div>
    </div>
  );
}

// packages/web/src/components/AppErrorFallback.vue
<!-- What ErrorBoundary.vue shows in place of a crashed tree — mirrors
     packages/web/src/components/AppErrorFallback.tsx. -->
<script setup lang="ts">
import { useT } from '../i18n';

defineProps<{ retry: () => void }>();
const t = useT();
</script>

<template>
  <div class="page error-page" role="alert">
    <h1>{{ t.error.title }}</h1>
    <p>{{ t.error.body }}</p>
    <div class="error-actions">
      <button type="button" class="btn btn-primary" @click="retry">{{ t.error.reload }}</button>
      <RouterLink class="btn" to="/">{{ t.error.home }}</RouterLink>
    </div>
  </div>
</template>
