// packages/web/src/components/ThemeToggle.vue
<!-- Mirrors packages/web/src/components/ThemeToggle.tsx — see that file for why these are
     monochrome stroke icons rather than emoji. -->
<script setup lang="ts">
import { useTheme } from '../composables/theme';
import { useT } from '../i18n';

const { state, toggleTheme } = useTheme();
const t = useT();
</script>

<template>
  <button
    type="button"
    class="theme-toggle"
    :aria-label="state.theme === 'light' ? t.theme.toDark : t.theme.toLight"
    :title="state.theme === 'light' ? t.theme.toDark : t.theme.toLight"
    @click="toggleTheme"
  >
    <svg v-if="state.theme === 'light'" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z" />
    </svg>
    <svg v-else viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <circle cx="12" cy="12" r="4" />
      <path
        d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"
      />
    </svg>
  </button>
</template>

// packages/web/src/components/ThemeToggle.tsx
import { useTheme } from '../context/ThemeContext';
import { useT } from '../i18n';

export default function ThemeToggle() {
  const { theme, toggleTheme } = useTheme();
  const t = useT();
  const label = theme === 'light' ? t.theme.toDark : t.theme.toLight;

  return (
    <button
      type="button"
      onClick={toggleTheme}
      className="theme-toggle"
      aria-label={label}
      title={label}
    >
      {theme === 'light' ? '🌙' : '☀️'}
    </button>
  );
}
